[tools]
bitwarden = "latest"
"github:anomalyco/opencode" = "latest"
node = "22.16"
"npm:@google/gemini-cli" = "latest"
"npm:tldr" = "latest"
ruby = "3.3.0"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
